### ISSUE TITLE
docs/examples

### ISSUE THREAD

**Issue by dev-dsp** [mwatts15/YAROM#10]
hello,

I've tried running the example provided in https://yarom.readthedocs.io/en/latest/adding_data.html, but found that it doesn't work - e.g. Y.DataObject should now probably be Y.dataObject.DataObject, also could not find definition of UnionProperty and so on.

Could you please share some working examples and probably update dev branch with them?

Thanks

**Comment by mwatts15** [comment]
Hi, @dev-dsp . Most development has shifted back to PyOpenWorm. When PyOpenWorm R1 is out, we'll clean up this repo as well.
